#%RAML 1.0 NamedExample
value:
  {
    "title": "Stiff: The Curious Lives of Human Cadavers",
    "description": "Stiff: The Curious Lives of Human Cadavers",
    "genre": "science",
    "author": "Mary Roach",
    "link": "http://e-bookmobile.com/books/Stiff"
  }